version: '3'

services:
    nginx:
        image: nginx
        volumes:
            - ./nginx/certbot/conf:/etc/letsencrypt
            - ./nginx/certbot/www:/var/www/certbot
            - ./nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "80:80"
            - "443:443"
        network_mode: "host"
    certbot:
        image: certbot/certbot
        volumes:
            - ./nginx/certbot/conf:/etc/letsencrypt
            - ./nginx/certbot/www:/var/www/certbot
    web:
        build: './api'
        depends_on:
            - nginx
        ports:
            - "8000:8000"
        network_mode: "host"
